# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pricing_pb2 as pricing__pb2
import test_pb2 as test__pb2


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.train_add = channel.unary_unary(
                '/example_service.Calculator/train_add',
                request_serializer=test__pb2.TrainingRequest.SerializeToString,
                response_deserializer=test__pb2.TrainingResponse.FromString,
                )
        self.train_subtraction = channel.unary_unary(
                '/example_service.Calculator/train_subtraction',
                request_serializer=test__pb2.TrainingRequest.SerializeToString,
                response_deserializer=test__pb2.TrainingResponse.FromString,
                )
        self.dynamic_pricing_train_add = channel.unary_unary(
                '/example_service.Calculator/dynamic_pricing_train_add',
                request_serializer=test__pb2.TrainingRequest.SerializeToString,
                response_deserializer=pricing__pb2.PriceInCogs.FromString,
                )
        self.dynamic_pricing_add = channel.unary_unary(
                '/example_service.Calculator/dynamic_pricing_add',
                request_serializer=test__pb2.Numbers.SerializeToString,
                response_deserializer=pricing__pb2.PriceInCogs.FromString,
                )
        self.add = channel.unary_unary(
                '/example_service.Calculator/add',
                request_serializer=test__pb2.Numbers.SerializeToString,
                response_deserializer=test__pb2.Result.FromString,
                )
        self.sub = channel.unary_unary(
                '/example_service.Calculator/sub',
                request_serializer=test__pb2.Numbers.SerializeToString,
                response_deserializer=test__pb2.Result.FromString,
                )
        self.mul = channel.unary_unary(
                '/example_service.Calculator/mul',
                request_serializer=test__pb2.Numbers.SerializeToString,
                response_deserializer=test__pb2.Result.FromString,
                )
        self.div = channel.unary_unary(
                '/example_service.Calculator/div',
                request_serializer=test__pb2.Numbers.SerializeToString,
                response_deserializer=test__pb2.Result.FromString,
                )


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def train_add(self, request, context):
        """AI developer can define their own training methods , if you wish to have a different pricing , please use
        define the pricing method as shown below, dynamic_pricing_train_add, please make sure the i/p is exactly the same
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def train_subtraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dynamic_pricing_train_add(self, request, context):
        """make sure the params to the method are exactly the same as that of the method in which needs
        dynamic price computation

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dynamic_pricing_add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mul(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def div(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'train_add': grpc.unary_unary_rpc_method_handler(
                    servicer.train_add,
                    request_deserializer=test__pb2.TrainingRequest.FromString,
                    response_serializer=test__pb2.TrainingResponse.SerializeToString,
            ),
            'train_subtraction': grpc.unary_unary_rpc_method_handler(
                    servicer.train_subtraction,
                    request_deserializer=test__pb2.TrainingRequest.FromString,
                    response_serializer=test__pb2.TrainingResponse.SerializeToString,
            ),
            'dynamic_pricing_train_add': grpc.unary_unary_rpc_method_handler(
                    servicer.dynamic_pricing_train_add,
                    request_deserializer=test__pb2.TrainingRequest.FromString,
                    response_serializer=pricing__pb2.PriceInCogs.SerializeToString,
            ),
            'dynamic_pricing_add': grpc.unary_unary_rpc_method_handler(
                    servicer.dynamic_pricing_add,
                    request_deserializer=test__pb2.Numbers.FromString,
                    response_serializer=pricing__pb2.PriceInCogs.SerializeToString,
            ),
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=test__pb2.Numbers.FromString,
                    response_serializer=test__pb2.Result.SerializeToString,
            ),
            'sub': grpc.unary_unary_rpc_method_handler(
                    servicer.sub,
                    request_deserializer=test__pb2.Numbers.FromString,
                    response_serializer=test__pb2.Result.SerializeToString,
            ),
            'mul': grpc.unary_unary_rpc_method_handler(
                    servicer.mul,
                    request_deserializer=test__pb2.Numbers.FromString,
                    response_serializer=test__pb2.Result.SerializeToString,
            ),
            'div': grpc.unary_unary_rpc_method_handler(
                    servicer.div,
                    request_deserializer=test__pb2.Numbers.FromString,
                    response_serializer=test__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example_service.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def train_add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example_service.Calculator/train_add',
            test__pb2.TrainingRequest.SerializeToString,
            test__pb2.TrainingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def train_subtraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example_service.Calculator/train_subtraction',
            test__pb2.TrainingRequest.SerializeToString,
            test__pb2.TrainingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def dynamic_pricing_train_add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example_service.Calculator/dynamic_pricing_train_add',
            test__pb2.TrainingRequest.SerializeToString,
            pricing__pb2.PriceInCogs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def dynamic_pricing_add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example_service.Calculator/dynamic_pricing_add',
            test__pb2.Numbers.SerializeToString,
            pricing__pb2.PriceInCogs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example_service.Calculator/add',
            test__pb2.Numbers.SerializeToString,
            test__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example_service.Calculator/sub',
            test__pb2.Numbers.SerializeToString,
            test__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def mul(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example_service.Calculator/mul',
            test__pb2.Numbers.SerializeToString,
            test__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def div(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example_service.Calculator/div',
            test__pb2.Numbers.SerializeToString,
            test__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
