# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import training_pb2 as training__pb2
import pricing_pb2 as pricing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x0f\x65xample_service\x1a\x0etraining.proto\x1a\rpricing.proto\"5\n\x0b\x41\x64\x64ressList\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x03(\t\x12\x15\n\rmodel_details\x18\x02 \x01(\t\"1\n\x07Numbers\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\x12\x10\n\x08model_id\x18\x03 \x01(\t\"\x17\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1b\n\x07ModelId\x12\x10\n\x08model_id\x18\x01 \x01(\t\"V\n\x0fTrainingRequest\x12\x0c\n\x04link\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\"V\n\x10TrainingResponse\x12\x0c\n\x04link\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t2\x92\x06\n\nCalculator\x12\x99\x01\n\ttrain_add\x12 .example_service.TrainingRequest\x1a!.example_service.TrainingResponse\"G\xba\xb1\x92&7\n5/example_service.Calculator/dynamic_pricing_train_add\xea\xb5\x92&\x06\n\x04true\x12\xa1\x01\n\x11train_subtraction\x12 .example_service.TrainingRequest\x1a!.example_service.TrainingResponse\"G\xba\xb1\x92&7\n5/example_service.Calculator/dynamic_pricing_train_add\xea\xb5\x92&\x06\n\x04true\x12U\n\x19\x64ynamic_pricing_train_add\x12 .example_service.TrainingRequest\x1a\x14.pricing.PriceInCogs\"\x00\x12G\n\x13\x64ynamic_pricing_add\x12\x18.example_service.Numbers\x1a\x14.pricing.PriceInCogs\"\x00\x12p\n\x03\x61\x64\x64\x12\x18.example_service.Numbers\x1a\x17.example_service.Result\"6\xba\xb1\x92&1\n//example_service.Calculator/dynamic_pricing_add\x12:\n\x03sub\x12\x18.example_service.Numbers\x1a\x17.example_service.Result\"\x00\x12:\n\x03mul\x12\x18.example_service.Numbers\x1a\x17.example_service.Result\"\x00\x12:\n\x03\x64iv\x12\x18.example_service.Numbers\x1a\x17.example_service.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _CALCULATOR.methods_by_name['train_add']._options = None
  _CALCULATOR.methods_by_name['train_add']._serialized_options = b'\272\261\222&7\n5/example_service.Calculator/dynamic_pricing_train_add\352\265\222&\006\n\004true'
  _CALCULATOR.methods_by_name['train_subtraction']._options = None
  _CALCULATOR.methods_by_name['train_subtraction']._serialized_options = b'\272\261\222&7\n5/example_service.Calculator/dynamic_pricing_train_add\352\265\222&\006\n\004true'
  _CALCULATOR.methods_by_name['add']._options = None
  _CALCULATOR.methods_by_name['add']._serialized_options = b'\272\261\222&1\n//example_service.Calculator/dynamic_pricing_add'
  _globals['_ADDRESSLIST']._serialized_start=62
  _globals['_ADDRESSLIST']._serialized_end=115
  _globals['_NUMBERS']._serialized_start=117
  _globals['_NUMBERS']._serialized_end=166
  _globals['_RESULT']._serialized_start=168
  _globals['_RESULT']._serialized_end=191
  _globals['_MODELID']._serialized_start=193
  _globals['_MODELID']._serialized_end=220
  _globals['_TRAININGREQUEST']._serialized_start=222
  _globals['_TRAININGREQUEST']._serialized_end=308
  _globals['_TRAININGRESPONSE']._serialized_start=310
  _globals['_TRAININGRESPONSE']._serialized_end=396
  _globals['_CALCULATOR']._serialized_start=399
  _globals['_CALCULATOR']._serialized_end=1185
# @@protoc_insertion_point(module_scope)
